[package]
name = "chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
gdnative = "0.9.3"
termcolor = "1.1.2"

[lib]
crate-type = ["cdylib"]
